# Generated by Django 6.0.3 on 2026-04-22 17:20

import documents.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='acta_nacimiento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='comprobante_bancario',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='constancia_fiscal',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='curp',
            field=documents.fields.EncryptedCharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='domicilio',
            field=documents.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ine',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='nombre_completo',
            field=documents.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rfc',
            field=documents.fields.EncryptedCharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='telefono',
            field=documents.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='note',
            field=documents.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=documents.fields.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='documentcomment',
            name='comment',
            field=documents.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='note',
            field=documents.fields.EncryptedTextField(blank=True),
        ),
    ]
