# Generated by Django 6.0.3 on 2026-04-22 17:41

import django.db.models.deletion
import documents.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_acta_nacimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='credit_type',
            field=models.CharField(choices=[('credito', 'Crédito Personal'), ('tarjeta', 'Tarjeta de Crédito')], default='credito', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='erp_export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='erp_exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_details',
            field=documents.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('ilegible', 'Documento ilegible'), ('no_coinciden', 'Datos no coinciden entre documentos'), ('curp_invalido', 'CURP/RFC inválido o no existe'), ('buro_credito', 'En buró de crédito'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator1_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='validator1_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator1_comment',
            field=documents.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator2_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='validator2_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator2_comment',
            field=documents.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validator2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending_validator1', 'Espera Validador 1'), ('validator1_review', 'En revisión Validador 1'), ('pending_validator2', 'Espera Validador 2'), ('validator2_review', 'En revisión Validador 2'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending_validator1', max_length=30),
        ),
    ]
