# Generated by Django 6.0.3 on 2026-04-22 22:39

import django.db.models.deletion
import documents.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_credit_type_document_erp_export_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', documents.fields.EncryptedCharField(max_length=255)),
                ('curp', documents.fields.EncryptedCharField(max_length=18)),
                ('rfc', documents.fields.EncryptedCharField(max_length=13)),
                ('domicilio', documents.fields.EncryptedCharField(max_length=500)),
                ('telefono', documents.fields.EncryptedCharField(max_length=20)),
                ('credit_type', models.CharField(max_length=20)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='erp_record', to='documents.document')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportación a ERP',
                'verbose_name_plural': 'Exportaciones a ERP',
            },
        ),
    ]
