# Generated by Django 6.0.3 on 2026-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_erpexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('validator1', 'Validador Nivel 1'), ('validator2', 'Validador Nivel 2'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
