# Generated by Django 6.0.3 on 2026-04-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
