# Generated by Django 6.0.3 on 2026-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_auditlog_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('validator1', 'STAFF'), ('validator2', 'SENIOR'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
