# Generated by Django 6.0.3 on 2026-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_file_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='curp_documento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/docs/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending_validator1', 'Espera STAFF'), ('validator1_review', 'En revisión STAFF'), ('pending_validator2', 'Espera SENIOR'), ('validator2_review', 'En revisión SENIOR'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending_validator1', max_length=30),
        ),
    ]
