# Generated by Django 6.0.3 on 2026-05-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_curp_documento_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clicked_continuidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
